<a href="https://colab.research.google.com/github/Johanhms/Learning_Python/blob/main/DataScience_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Types of Variable**

In [ ]:
counter = 0
while counter < 12:
  print(counter)
  counter = counter + 1


0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for i in range(5):
  print("Hello")

Hello
Hello
Hello
Hello
Hello


In [ ]:
for i in range(5):
  print("Hello: ", i)

Hello:  0
Hello:  1
Hello:  2
Hello:  3
Hello:  4


In [ ]:
mylist = [10,100,1000]

In [ ]:
for j in mylist:
  print("j is: ", j)

j is:  10
j is:  100
j is:  1000


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
randn()

0.966564236679124

In [ ]:
x = randn()
if x > 1:
  answer = "Greater than 1"
print(x)
print(answer)

2.2629430979297833
Greater than 1


In [ ]:
x = randn()
if x > 1:
  answer = "Greatter than 1"
else:
  answer = "Less than 1"
  print(x)
  print(answer)

-1.9342967483250317
Less than 1


In [ ]:
x = randn()
if x > 1:
  answer = "Greater than 1"
else:
    if x >=-1:
      answer = "Between -1 and 1"
    else:
      answer = "Less than -1"
print(x)
print(answer)

-0.10769703913430084
Between -1 and 1


In [ ]:
x = randn()
if x > 1:
  answer = "Greater than 1"
elif x >= -1:
  answer = "Between -1 and 1"
else:
  answer = "Less than -1"
print(x)
print(answer)

-0.06348372607557588
Between -1 and 1


In [ ]:
counter  = 0
while counter < 4:
  print("abra")
  counter = counter + 1

abra
abra
abra
abra


## **Fundamental of Python**

In [ ]:
w = list(range(100,200,10))

In [ ]:
w[0]

100

In [ ]:
len(w)

10

In [ ]:
w[-3]

170

In [ ]:
w[-1]


190

In [ ]:
w[9]

190

In [ ]:
w[2] = 2

In [ ]:
w

[100, 110, 2, 130, 140, 150, 160, 170, 180, 190]

In [ ]:
w[::-1]

[190, 180, 170, 160, 150, 140, 130, 2, 110, 100]

In [ ]:
myList = list(range(20,31))

In [ ]:
len(myList)

11

In [ ]:
type(mylist)

list

In [ ]:
max(myList)

30

In [ ]:
a = np.array(myList)


In [ ]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
mylist.append(10)


In [ ]:
a.mean()

25.0



##**NumPy**



In [1]:
import numpy as np

In [3]:
np.random.randn(5,5)

array([[ 0.28600552, -0.00698919,  0.11737739, -0.79545267, -0.86386242],
       [-0.19657888, -0.02878489, -0.82736057, -0.93235976,  1.53398768],
       [ 0.8072843 , -0.09061811, -1.54337738, -0.07931692,  0.73794393],
       [-2.97725398,  0.47077131, -1.07683236, -0.68215316,  0.46343248],
       [-0.4833959 , -1.06943295, -0.87277726, -1.30180699,  0.79480352]])

In [7]:
np.random.randn(4,4)

array([[-0.50029033,  0.66411011,  1.21526375,  0.56861005],
       [ 1.85149338,  1.32183528,  1.27003312,  0.67513848],
       [-0.93955876, -0.20891845,  0.48330774,  0.30052566],
       [ 1.57136681,  1.60203473, -0.56952179,  0.13164167]])

In [9]:
np.random.randint(1,100,20)

array([59,  3, 50, 55, 16, 63, 71, 66,  8, 96, 27, 80, 85,  2, 59, 19,  5,
        9, 11, 93])

In [13]:
arr = np.arange(25)

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.max()

24

In [16]:
arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [20]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [29]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [30]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [31]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.rand(1)

array([0.03199268])

In [34]:
np.random.randn(25)

array([ 0.03189229,  1.0766765 ,  1.45656705, -0.81478902,  0.36366752,
       -1.01283297,  0.66972331,  0.5980334 , -0.70453421, -0.51102667,
       -0.57396948, -0.14026153,  0.37977153, -0.69509101,  1.33694012,
       -0.10289016, -2.07650652,  0.25652841,  0.90723268,  0.96432598,
        0.29553267, -0.47350869,  3.10691375, -1.23224801, -2.35966532])

In [35]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [40]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [42]:
mat = np.arange(1,26).reshape(5,5)

In [44]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [47]:
mat[3,4]

20

In [52]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [53]:
mat [4:]

array([[21, 22, 23, 24, 25]])

In [54]:
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
np.sum(mat)

325

In [57]:
mat.sum()

325

In [58]:
mat.std()

7.211102550927978

In [59]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

##**Pandas**